### ISSUE TITLE
question

### ISSUE THREAD

**Issue by t3chkn0w420** [CrystalX127/Shield#1]
how do u input command?
![Screenshot from 2020-08-11 15-21-20](https://user-images.githubusercontent.com/69204660/89940344-59476180-dbe7-11ea-9c0e-09eb15e777f3.png)

**Comment by TheOnodrim** [comment]
All you need to do is input, "Shield [Whichever command you choose from the list of commands]." For example, "Shield -info." I hope that answers your question.

**Comment by TheOnodrim** [comment]
Please leave a comment when you have read this comment, so that I can close this issue. Thanks!

**Comment by t3chkn0w420** [comment]
ohhhw. thank you thank you!

**Comment by t3chkn0w420** [comment]
maybe this isnt for me? haha
