### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by JamesC00** [CrystalX127/Shield#2]
./Shield.sh: line 1238: syntax error near unexpected token `Shield'
./Shield.sh: line 1238: `for example Shield purges old and removed packages to remove'

**Comment by TheOnodrim** [comment]
I believe I have fixed this problem as well as a couple more I ran into while fixing this one. Please comment so that I can close this issue(Assuming I fixed the problem in the first place).

**Comment by JamesC00** [comment]
yep that fixed it for me
